### ISSUE TITLE
Editing group permission exception

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#604] opened 2018-05-04 17:12 UTC
When a user is a member of a single group and group permissions are edited in the group modal, an exception occurs in sagaUtils. If the user is a member of multiple groups or no groups, group permission editing works as usual.

**Comment by igboyes** [comment] 2018-05-04 20:41
I'll check this out.

**Comment by igboyes** [comment] 2018-05-16 19:07
Duplicate of #639

**Closed** 2018-05-16 19:07 UTC
Labels: bug, to do
