### ISSUE TITLE
Connect to MongoDB

### ISSUE THREAD

**Issue by snunzi** [virtool/virtool#1403] opened 2019-07-11 14:09 UTC
While going through the initial setup, I cannot connect to MongoDB using connection string. I have Virtool v3.6.0-beta.1 running and have tried with MongoDB v 3.6.13 and 3.6.0. 

Is there a way to go through the entire setup manually on command line instead of on graphical interface?

**Comment by igboyes** [comment] 2019-07-11 16:05
I'm sorry for the rough start.

Can you post the lines from the MongoDB log file (`/var/log/mongodb/mongodb.log`) near the time of connection failure?

Setup via the command line is not fully supported, but is in the queue (#1314).

**Comment by snunzi** [comment] 2019-07-11 16:56
Excited to use the software, and thankful for your help in getting it up and running!

I'm having issues troubleshooting because the log file doesn't show any activity for the time I'm trying to connect. 

[mongogb_virtool.log](https://github.com/virtool/virtool/files/3383109/mongogb_virtool.log)

[terminal_virtool.txt](https://github.com/virtool/virtool/files/3383128/terminal_virtool.txt)

**Comment by igboyes** [comment] 2019-07-11 17:30
You may have tried this already. Can you make sure the you can open a Mongo shell using the command `mongo`?

If that works, please issue the command `show dbs` in the shell. Post the output. Also, please post your connection string if it isn't sensitive.

I am going to be releasing v3.6.0-beta.2 soon. I will include some better logging in Virtool to try to diagnose this issue.

**Comment by snunzi** [comment] 2019-07-11 17:52
Can open a mongo shell, but haven't created any databases. Will download the new version when it's released.

[mongo_shell.txt](https://github.com/virtool/virtool/files/3383305/mongo_shell.txt)

**Comment by igboyes** [comment] 2019-07-17 16:56
v3.6.0-beta.2 is now released @snunzi. This isn't going to fix the problem, but should log some more information so I can figure it out.

**Comment by igboyes** [comment] 2019-09-19 16:40
@snunzi I'm working on a potential fix for this that should be ready to try today. I'm not exactly sure what the issue is, since I can't reproduce it.

Are you using a Python virtual environment for running virtool?

**Comment by snunzi** [comment] 2019-09-19 18:16
I really appreciate all your help with this.

I am using a conda environment to run virtool. I tried initially to set it
up without the environment, but ran into a lot of dependency issues.

**Comment by igboyes** [comment] 2019-09-19 18:35
I am not a seasoned conda user, so can't provide much help.

Please ensure the installed packages in your environment are up-to-date with `requirements.txt`. The issue seems to be linked to a change in one of the dependencies ([`motor-1.3.1`](https://motor.readthedocs.io/en/stable/)).

If you are using `pip` in conda, you can just run `pip install -r requirements.txt`, I think. You can make sure the correct version of `motor` is installed using `pip show motor`. The version should be `1.3.1`.

I have also released v3.7.4 that updates the usage of this dependency in Virtool.

**Comment by snunzi** [comment] 2019-09-19 19:04
That solved it, my version of motor was the latest version! Was able to get it configured. Many thanks!

**Comment by igboyes** [comment] 2019-09-19 20:30
Yay! Keep in touch.

**Closed by igboyes** 2019-09-19 20:30 UTC
