### ISSUE TITLE
Server error on GET subtraction request

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#1057] opened 2018-07-24 17:17 UTC
Results in [this error](https://sentry.io/cph/server/issues/618866453/?query=is:unresolved)

```
Traceback (most recent call last):
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/naomis/Projects/virtool/virtool/http/errors.py", line 16, in middleware
    response = await handler(req)
  File "/home/naomis/Projects/virtool/virtool/http/proxy.py", line 69, in middleware
    return await handler(req)
  File "/home/naomis/Projects/virtool/virtool/app_auth.py", line 100, in middleware
    response = await handler(req)
  File "/home/naomis/Projects/virtool/virtool/http/routes.py", line 81, in wrapped
    return await handler(req)
  File "/home/naomis/Projects/virtool/virtool/api/subtractions.py", line 65, in get
    document["linked_samples"] = await virtool.db.subtractions.get_linked_samples(db, subtraction_id)
  File "/home/naomis/Projects/virtool/virtool/db/subtractions.py", line 13, in get_linked_samples
    cursor = await db.samples.find({"subtraction.id": subtraction_id}, ["name"])
TypeError: object AsyncIOMotorCursor can't be used in 'await' expression
```

**Comment by igboyes** [comment] 2018-07-24 17:18
Duplicate of #1056.

PR in progress.

**Closed by igboyes** 2018-07-24 17:18 UTC
