### ISSUE TITLE
Error for NuVs analysis

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#429] opened 2018-03-06 16:58 UTC
web_protocol ERROR    Error handling request
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
  File "/home/travis/build/virtool/virtool/virtool/proxy.py", line 68, in middleware
  File "/home/travis/build/virtool/virtool/virtool/error_pages.py", line 15, in middleware
  File "/home/travis/build/virtool/virtool/virtool/app_auth.py", line 96, in middleware
  File "/home/travis/build/virtool/virtool/virtool/handlers/samples.py", line 71, in find
  File "/home/travis/build/virtool/virtool/virtool/handlers/utils.py", line 90, in json_response
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_response.py", line 641, in json_response
  File "/home/travis/build/virtool/virtool/virtool/handlers/utils.py", line 35, in dumps
  File "/opt/python/3.6.3/lib/python3.6/json/__init__.py", line 238, in dumps
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 201, in encode
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 437, in _iterencode
  File "/home/travis/build/virtool/virtool/virtool/handlers/utils.py", line 20, in default
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 180, in default
TypeError: Object of type 'Response' is not JSON serializable
Sending message of length 4955 to https://sentry.io/api/220532/store/

**Comment by igboyes** [comment] 2018-03-06 17:09
Thanks.

Duplicate of #397

**Closed** 2018-03-09 23:56 UTC
Labels: bug, in progress

**Comment by igboyes** [comment] 2018-03-10 00:25
@maplexuci 
This should finally be fixed in **v2.1.1** which I just released.

**Comment by maplexuci** [comment] 2018-03-12 16:10
In V2.1.1, the NuVs analysis is not able to be selected from the Sample--New Analysis drop-down list.

**Comment by igboyes** [comment] 2018-03-12 17:13
New issue is #456.

I'll fix this ASAP.

**Comment by igboyes** [comment] 2018-03-12 19:39
@maplexuci 

Issue is fixed in release v2.1.2.

**Comment by maplexuci** [comment] 2018-03-13 20:51
Still god a error, this is the message from the terminal:
web_protocol ERROR    Error handling request
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
  File "/home/travis/build/virtool/virtool/virtool/proxy.py", line 68, in middleware
  File "/home/travis/build/virtool/virtool/virtool/error_pages.py", line 15, in middleware
  File "/home/travis/build/virtool/virtool/virtool/app_auth.py", line 96, in middleware
  File "/home/travis/build/virtool/virtool/virtool/handlers/updates.py", line 16, in get
  File "/home/travis/build/virtool/virtool/virtool/updates.py", line 62, in get_releases
  File "/home/travis/build/virtool/virtool/virtool/updates.py", line 62, in <listcomp>
TypeError: string indices must be integers

Here is the message from the job logs:
2018-03-12T19:46:01.214000    Stage: check_db
2018-03-12T19:46:01.218000    Stage: mk_analysis_dir
2018-03-12T19:46:01.218000    Process: mkdir
2018-03-12T19:46:01.292000    Stage: map_viruses
2018-03-12T19:46:01.292000    Command: bowtie2 -p 6 -k 1 --very-fast-local -x data/reference/viruses/lvvfnxct/reference --un data/samples/uvwrpthe/analysis/wpeceuly/unmapped_viruses.fq -U data/samples/uvwrpthe/reads_1.fastq
2018-03-12T19:50:04.737000        b'6861120 reads; of these:'
2018-03-12T19:50:04.738000        b'  6861120 (100.00%) were unpaired; of these:'
2018-03-12T19:50:04.738000        b'    3981889 (58.04%) aligned 0 times'
2018-03-12T19:50:04.738000        b'    2879231 (41.96%) aligned exactly 1 time'
2018-03-12T19:50:04.738000        b'    0 (0.00%) aligned >1 times'
2018-03-12T19:50:04.738000        b'41.96% overall alignment rate'
2018-03-12T19:50:04.774000    Stage: map_subtraction
2018-03-12T19:50:04.775000    Command: bowtie2 --very-fast-local -k 1 -p 6 -x data/reference/subtraction/phaseolus_vulgaris.common_bean/reference --un data/samples/uvwrpthe/analysis/wpeceuly/unmapped_hosts.fq -U data/samples/uvwrpthe/analysis/wpeceuly/unmapped_viruses.fq
2018-03-12T19:51:16.985000        b'3981889 reads; of these:'
2018-03-12T19:51:16.985000        b'  3981889 (100.00%) were unpaired; of these:'2018-03-12T19:51:16.987000        b'    3364963 (84.51%) aligned 0 times'
2018-03-12T19:51:16.987000        b'    616926 (15.49%) aligned exactly 1 time'
2018-03-12T19:51:16.987000        b'    0 (0.00%) aligned >1 times'
2018-03-12T19:51:16.987000        b'15.49% overall alignment rate'
2018-03-12T19:51:16.989000    Stage: reunite_pairs
2018-03-12T19:51:16.990000    Stage: assemble
2018-03-12T19:51:16.992000    Command: spades.py -t 5 -m 16 -s data/samples/uvwrpthe/analysis/wpeceuly/unmapped_hosts.fq -o /tmp/tmphvibrcw2 -k 21,33,55,75

**Comment by igboyes** [comment] 2018-03-14 15:59
This is two separate problems:

The first (`TypeError: string indices must be integers`) is due to a problem with [www.virtool.ca](https://www.virtool.ca) that has been resolved. Create a new issue if it is persisting for some reason.

The second error is a recurring problem that I haven't been able to figure out. Would you be able to provide me with the FASTQ data that is causing this error? It should help me get rid of this bug. Duplicate of #325. We can continue discussion in #325.

I'm locking this issue. Please open new issues for future problems unrelated to this thread.
