### ISSUE TITLE
Object of type 'Response' is not JSON serializable

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#397] opened 2018-02-21 20:40 UTC
Here is the error message every time a job is done. Have to refresh the browser to normally display the GUI.

web_protocol ERROR    Error handling request
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
  File "/home/travis/build/virtool/virtool/virtool/proxy.py", line 68, in middleware
  File "/home/travis/build/virtool/virtool/virtool/error_pages.py", line 15, in middleware
  File "/home/travis/build/virtool/virtool/virtool/app_auth.py", line 96, in middleware
  File "/home/travis/build/virtool/virtool/virtool/handlers/samples.py", line 71, in find
  File "/home/travis/build/virtool/virtool/virtool/handlers/utils.py", line 90, in json_response
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_response.py", line 641, in json_response
  File "/home/travis/build/virtool/virtool/virtool/handlers/utils.py", line 35, in dumps
  File "/opt/python/3.6.3/lib/python3.6/json/__init__.py", line 238, in dumps
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 201, in encode
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 437, in _iterencode
  File "/home/travis/build/virtool/virtool/virtool/handlers/utils.py", line 20, in default
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 180, in default
TypeError: Object of type 'Response' is not JSON serializable
Sending message of length 5515 to https://sentry.io/api/220532/store/

**Comment by igboyes** [comment] 2018-02-21 21:11
Duplicate of #329

**Comment by igboyes** [comment] 2018-02-21 21:12
I thought this had been dealt with. There is a potential fix in **v2.0.5**. We can revisit after you have installed that.

**Comment by igboyes** [comment] 2018-03-01 22:48
@maplexuci 
Have you experienced this error again since **v2.0.5**?

**Comment by maplexuci** [comment] 2018-03-01 22:55
I just test it by creating a sample, no error message shows up. It looks good now.

**Comment by igboyes** [comment] 2018-03-01 22:57
Great, thanks. I'll close this again.

**Comment by igboyes** [comment] 2018-03-06 17:09
Regressed in #429

**Comment by igboyes** [comment] 2018-03-09 23:28
https://sentry.io/cph/server/issues/471158680/

**Closed** 2018-03-09 23:56 UTC
Labels: bug, in progress
