### ISSUE TITLE
Virtool fails to start after initial setup when MongoDB is on a different server

### ISSUE THREAD

**Issue by eburgueno** [virtool/virtool#373] opened 2018-02-13 21:53 UTC
After starting Virtool for the first time, I configured the connection to a MongoDB database running on a different server `mongodb`. This was stored in `settings.json` as follows:

```
    "db_host": "mongodb",
    "db_name": "virtool",
    "db_port": 27017,
```

However, after clicking 'Save and Reload', Virtool failed to start with the following error:

```
2018-02-12 23:30:40  base        DEBUG    Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7efc33c4eb00>
2018-02-12 23:30:41  app         INFO     Starting database checks. Do not interrupt. This may take several minutes.
2018-02-12 23:30:41  app         INFO     Checking viruses...
Sending message of length 3544 to https://sentry.io/api/220532/store/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run.py", line 58, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 439, in run_app
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 263, in startup
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/signals.py", line 51, in send
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/signals.py", line 17, in _send
  File "/home/travis/build/virtool/virtool/virtool/app.py", line 100, in init_db
  File "/home/travis/build/virtool/virtool/virtool/organize.py", line 16, in organize_viruses
  File "/opt/python/3.6.3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/collection.py", line 2059, in distinct
  File "/opt/python/3.6.3/lib/python3.6/contextlib.py", line 81, in __enter__
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
  File "/opt/python/3.6.3/lib/python3.6/contextlib.py", line 81, in __enter__
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/topology.py", line 214, in select_server
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/topology.py", line 189, in select_servers
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

Setting up MongoDB on the same server as Virtool (`localhost`) seems to work.

**Comment by igboyes** [comment] 2018-02-13 23:47
Thank you for your detailed report.

I've determined the cause of the error and am testing a solution.

Fix will be included in next release (v2.0.4) in next few days.

**Comment by eburgueno** [comment] 2018-02-13 23:50
Thanks Ian. This is crucial when using Docker/K8S, as the preferred pattern is to spin up MongoDB as a separate container than the app.

FYI, my `Dockerfile` is basically ready. I'd like to also create a `docker-compose.yml` for easy testing. Once this issue is fixed I will try and work on that before submitting a PR.

**Closed** 2018-02-14 23:30 UTC
Labels: bug, in progress

**Comment by Commifreak** [comment] 2020-06-23 04:34
> 
> 
> Thanks Ian. This is crucial when using Docker/K8S, as the preferred pattern is to spin up MongoDB as a separate container than the app.
> 
> FYI, my `Dockerfile` is basically ready. I'd like to also create a `docker-compose.yml` for easy testing. Once this issue is fixed I will try and work on that before submitting a PR.

Anything new regarding docker?

**Comment by igboyes** [comment] 2020-06-23 16:00
It is a major priority right now. We are working to deploy on Azure. Stay tuned.
